[package]
name = "daemon"
version = "0.1.0"
edition = "2021"
authors = ["Edoardo Bompiani"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs =  {version="0.17.0"}
specs-derive = "0.4.1"
rltk = { version="0.8.1" }
